### ISSUE TITLE
Enhance Image

### ISSUE THREAD

**Issue by domcouhrik** [domcouhrik/shapesge#3]
- [x] Create methods for resizing the images, as well as flipping horizontally and vertically.
- [ ] Also (potentially) create a method to change the anchor point, for both position and rotation (to enable creating e.g. skeletal bodies by anchoring multiple images to one point).
- [ ] Explore potential performance improvements by utilising SpriteSheets instead of separate files.

**Comment by domcouhrik** [comment]
### _**Tasks on hold**_
Tasks 2 and 3 are on hold for now, due to the sheer complexity + potentially unnecessary.

**Comment by domcouhrik** [comment]
### Performance issues
It seems the engine is only capable of processing 120-ish `Image`s using simplistic methods (single-threaded game code) before the FPS tanks completely (on a Ryzen 5700U). This should be fine for projects of Informatika 1 and 2 scale though.
